package com.yeihc.infrastructure.persistence.jpa;

import com.yeihc.domain.model.Transfer;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;
import java.util.UUID;

/**
 * Infrastructure Adapter: Spring Data JPA implementation for Transfer persistence.
 *
 * <p>This repository is the backbone of the system's reliability. It handles the
 * physical storage of transfer records and provides the necessary hooks for
 * implementing <b>Idempotency</b> at the database level.</p>
 *
 * <p><b>DESIGN DECISIONS:</b></p>
 * <ul>
 * <li><b>Idempotency Shield:</b> By providing a lookup for 'idempotencyKey', this
 * repository allows the system to detect and prevent duplicate financial operations
 * caused by network retries or client-side double-submissions.</li>
 * <li><b>Immutable Audit Trail:</b> Transfers are designed as historical records.
 * Once saved, they provide a permanent link between source and destination accounts.</li>
 * <li><b>Atomic Persistence:</b> Works in conjunction with the transaction manager
 * to ensure that transfer records are committed only if all related account balance
 * updates are successful.</li>
 * </ul>
 */
@Repository
public interface SpringDataTransferRepository extends JpaRepository<Transfer, UUID> {

    /**
     * Finds a previously processed transfer using its unique idempotency identifier.
     * * <p>In a financial context, if a client sends a transfer request and doesn't
     * receive a response (due to a timeout), they will retry with the same key.
     * This method allows the system to recognize that the transfer was already
     * executed and return the original result instead of processing it again.</p>
     *
     * @param idempotencyKey A unique string (usually a UUID or Hash) generated by
     * the client or the edge-service.
     * @return An Optional containing the original Transfer if it exists.
     */
    Optional<Transfer> findByIdempotencyKey(String idempotencyKey);
}